In [21]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
import statistics as st

# Libraries For Text

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import confusion_matrix
%matplotlib inline

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [22]:
text = "I love this movies!"
tokens = word_tokenize(text)
tokens

['I', 'love', 'this', 'movies', '!']

In [24]:
lower_tokens = [token.lower() for token in tokens]
lower_tokens

['i', 'love', 'this', 'movies', '!']

In [ ]:
# Filtering Symbolic sign like  ,!~?

In [25]:
stopwords = set(stopwords.words('english'))
filtered_tokens = [token for token in lower_tokens if token not in stopwords]
filtered_tokens

['love', 'movies', '!']

In [26]:
# Now Removing exclamatory sign (!)

import re

clean_tokens = [re.sub(r'[^\w\s]' , '' , token) for token in filtered_tokens]
clean_tokens

['love', 'movies', '']

In [ ]:
# Import libraries for feature extraction

In [27]:
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer

In [29]:
corpus = ['I love this movie!' , 'This movie is great.' , "I don't like this movie."]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(  X.toarray() )

['don' 'great' 'is' 'like' 'love' 'movie' 'this']
[[0 0 0 0 1 1 1]
 [0 1 1 0 0 1 1]
 [1 0 0 1 0 1 1]]


In [30]:
corpus = ['I love this movie!' , 'This movie is great.' , "I don't like this movie."]
Vectorizer = TfidfVectorizer()
X = Vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(  X.toarray() )

['don' 'great' 'is' 'like' 'love' 'movie' 'this']
[[0.         0.         0.         0.         0.76749457 0.45329466
  0.45329466]
 [0.         0.6088451  0.6088451  0.         0.         0.35959372
  0.35959372]
 [0.6088451  0.         0.         0.6088451  0.         0.35959372
  0.35959372]]
